version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/workspace
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      JVM_OPTS: -Xmx3200m
      TERM: dumb

commands:
  gradle-depenencies:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Install dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

jobs:
  test:
    executor: java-executor
    steps:
      - checkout
      - gradle-depenencies
      - run: ./gradlew test
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor: java-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - gradle-depenencies
      - run: ./gradlew build
      - run:
          name: Push new docker image
          command: ./gradlew jib

workflows:
  version: 2.1
  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
